# Generated by Django 4.2.30 on 2026-06-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='ai_nutrition_insights_batch_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='ai_pattern_insights_batch_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='weeklyreview',
            name='batch_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyreview',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
