# Generated by Django 4.2.30 on 2026-06-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_batch_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithingsAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=64)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expires_at', models.DateTimeField()),
                ('last_subscribed_at', models.DateTimeField(blank=True, null=True)),
                ('last_webhook_received_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_subscription_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Withings Auth',
                'verbose_name_plural': 'Withings Auth',
            },
        ),
    ]
