# Generated by Django 4.2.30 on 2026-06-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_add_withings_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='PelotonAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='peloton_session_id cookie', max_length=512)),
                ('user_id', models.CharField(help_text='Peloton user ID', max_length=64)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.CharField(blank=True, help_text="Optional — e.g. 'extracted from Chrome 2026-06-26'", max_length=500)),
            ],
            options={
                'verbose_name': 'Peloton Auth',
                'verbose_name_plural': 'Peloton Auth',
            },
        ),
    ]
