# Generated by Django 4.2.30 on 2026-06-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_add_peloton_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='last_daily_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
