# Generated by Django 4.2.30 on 2026-06-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_add_last_daily_sync_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sideeffectlog',
            name='other_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
