# Generated by Django 4.2.30 on 2026-07-05 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_add_side_effect_other_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('kind', models.CharField(choices=[('plan', 'Plan'), ('collection', 'Collection'), ('split', 'Split')], default='plan', max_length=20)),
                ('instructor', models.CharField(blank=True, max_length=120)),
                ('match_strategy', models.CharField(choices=[('achievement', 'Achievement name'), ('description', 'Description/title suffix'), ('ride_ids', 'Ride ID list')], default='ride_ids', max_length=20)),
                ('achievement_name', models.CharField(blank=True, max_length=150)),
                ('title_week_day_regex', models.CharField(blank=True, default='W(?:eek)?\\s*(?P<week>\\d+)[,\\s]*D(?:ay)?\\s*(?P<day>\\d+)', max_length=200)),
                ('series_id_hint', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProgramRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='workouts.program')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProgramWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, max_length=120)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='workouts.program')),
            ],
            options={
                'ordering': ['program', 'number'],
                'unique_together': {('program', 'number')},
            },
        ),
        migrations.CreateModel(
            name='RunWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('program_week', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.programweek')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_weeks', to='workouts.programrun')),
            ],
            options={
                'ordering': ['run', 'sequence'],
                'unique_together': {('run', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='ProgramSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('discipline', models.CharField(blank=True, max_length=40)),
                ('duration_min', models.PositiveIntegerField(blank=True, null=True)),
                ('peloton_ride_id', models.CharField(blank=True, max_length=64)),
                ('optional', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='workouts.programweek')),
            ],
            options={
                'ordering': ['week', 'day', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProgramWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_by', models.CharField(default='auto', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='workouts.runweek')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.programslot')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.cachedworkout')),
            ],
            options={
                'ordering': ['run_week', 'slot'],
                'unique_together': {('run_week', 'workout')},
            },
        ),
    ]
