# Generated by Django 4.2.30 on 2026-07-05 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_program_programrun_programweek_runweek_programslot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runweek',
            name='program_week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.programweek'),
        ),
    ]
