# Generated by Django 4.2.30 on 2026-07-05 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_alter_runweek_program_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='programslot',
            name='alt_ride_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
