# Generated by Django 4.2.30 on 2026-07-07 22:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_programslot_alt_ride_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='programrun',
            name='retrospective',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programrun',
            name='retrospective_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programrun',
            name='retrospective_model',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='runweek',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='runweek',
            name='rated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runweek',
            name='rpe',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
