# Generated by Django 4.2.30 on 2026-08-17 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_programrun_retrospective_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleHealthAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expires_at', models.DateTimeField()),
                ('scopes', models.TextField(blank=True, help_text='Space-separated granted scopes')),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Google Health Auth',
                'verbose_name_plural': 'Google Health Auth',
            },
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('peloton', 'Peloton'), ('garmin', 'Garmin'), ('withings', 'Withings'), ('google_health', 'Google Health')], max_length=32, unique=True)),
                ('display_name', models.CharField(max_length=64)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.AddField(
            model_name='cachedworkout',
            name='google_health_activity_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='google_health_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='wellness_source',
            field=models.CharField(blank=True, choices=[('garmin', 'Garmin'), ('google_health', 'Google Health')], max_length=16, null=True),
        ),
    ]
