# Generated by Django 4.2.30 on 2026-08-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0013_backfill_garmin_wellness_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystats',
            name='active_zone_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='hr_zone_light_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='hr_zone_moderate_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='hr_zone_peak_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='hr_zone_vigorous_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='sedentary_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='skin_temp_c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='skin_temp_deviation_c',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
