# Generated by Django 4.2.30 on 2026-08-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0014_dailystats_active_zone_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodentry',
            name='google_health_nutrition_log_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
