# Generated by Django 4.2.30 on 2026-08-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0015_foodentry_google_health_nutrition_log_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystats',
            name='resting_hr_baseline',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
