# Generated by Django 4.2.30 on 2026-08-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0016_dailystats_resting_hr_baseline'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystats',
            name='computed_readiness_label',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='computed_readiness_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='sleep_baseline_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='wellness_days_synced',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
