# Generated by Django 4.2.30 on 2026-08-23 02:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0018_webhookerror'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlehealthauth',
            name='connected_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
