# Generated by Django 4.2.30 on 2026-08-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0019_alter_googlehealthauth_connected_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedworkout',
            name='hr_zone_light_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cachedworkout',
            name='hr_zone_moderate_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cachedworkout',
            name='hr_zone_peak_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cachedworkout',
            name='hr_zone_vigorous_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
