# Generated by Django 4.2.30 on 2026-09-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0020_cachedworkout_hr_zone_light_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedworkout',
            name='class_plan_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cachedworkout',
            name='manual_movements_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
