# Generated by Django 4.2.30 on 2026-09-28 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0021_cachedworkout_class_plan_manual_movements'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='track_recovery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='programslot',
            name='match_discipline',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='programslot',
            name='match_title_keyword',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name='ProgramRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('walk', 'Cool-down walk'), ('stretch', 'Stretch')], max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('matched_by', models.CharField(default='auto', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to='workouts.programworkout')),
                ('workout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='program_recovery', to='workouts.cachedworkout')),
            ],
            options={
                'ordering': ['entry', 'order'],
            },
        ),
    ]
