# Generated by Django 4.2.30 on 2026-09-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0022_program_recovery_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='recovery_max_min',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='program',
            name='recovery_stretches',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='program',
            name='recovery_walks',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='program',
            name='recovery_window_min',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
