# Generated by Django 4.2.30 on 2026-10-02 23:38

from django.db import migrations, models


def set_db_default(apps, schema_editor):
    # DB-level default so code deployed before this migration (which omits the
    # column on INSERT) keeps working. Django 4.2 has no db_default; SQLite
    # already keeps the default from AddField's table rebuild.
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            "ALTER TABLE workouts_cachedworkout ALTER COLUMN user_corrected SET DEFAULT false"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0023_program_recovery_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedworkout',
            name='user_corrected',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_db_default, migrations.RunPython.noop),
    ]