# Generated by Django 4.2.30 on 2026-10-03 18:18

from django.db import migrations, models
import workouts.models


def set_db_default(apps, schema_editor):
    # DB-level default so code deployed before this migration (which omits the
    # column on INSERT) keeps working — same reason as 0024.
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            "ALTER TABLE workouts_usersettings ALTER COLUMN dumbbells_lb "
            "SET DEFAULT '[2, 5, 7, 10, 12, 15, 20, 25, 30, 35, 40, 45]'::jsonb"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0024_cachedworkout_user_corrected'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='dumbbells_lb',
            field=models.JSONField(blank=True, default=workouts.models.default_dumbbells),
        ),
        migrations.RunPython(set_db_default, migrations.RunPython.noop),
    ]
