# Generated by Django 4.2.30 on 2026-10-03 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0030_assign_singletons_to_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='googlehealthauth',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_health_auth', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nutritionprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pelotonauth',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='peloton_auth', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fp_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='withingsauth',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='withings_auth', to=settings.AUTH_USER_MODEL),
        ),
    ]
