# Generated by Django 4.2.30 on 2026-10-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0031_per_user_singletons_required'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='withingsauth',
            constraint=models.UniqueConstraint(condition=models.Q(('userid', ''), _negated=True), fields=('userid',), name='uniq_withings_userid'),
        ),
    ]
