# Generated by Django 4.2.30 on 2026-10-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0037_reset_id_sequences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelotonauth',
            name='session_id',
        ),
        migrations.AddField(
            model_name='pelotonauth',
            name='access_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pelotonauth',
            name='access_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pelotonauth',
            name='auth_error',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pelotonauth',
            name='auth_failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pelotonauth',
            name='connected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pelotonauth',
            name='refresh_rotated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pelotonauth',
            name='refresh_token',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pelotonauth',
            name='notes',
            field=models.CharField(blank=True, help_text="Optional — e.g. 'copied from Chrome 2026-10-03'", max_length=500),
        ),
    ]
