# Generated by Django 4.2.30 on 2026-10-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0038_peloton_auth_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='PelotonClassType',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('discipline', models.CharField(db_index=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PelotonInstructor',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PelotonClass',
            fields=[
                ('ride_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('discipline', models.CharField(db_index=True, max_length=40)),
                ('categories', models.CharField(blank=True, db_index=True, max_length=200)),
                ('class_type_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('class_type_ids', models.JSONField(blank=True, default=list)),
                ('instructor_id', models.CharField(blank=True, max_length=64)),
                ('instructor_name', models.CharField(blank=True, max_length=120)),
                ('duration_seconds', models.PositiveIntegerField(db_index=True)),
                ('length_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('difficulty_estimate', models.FloatField(blank=True, null=True)),
                ('difficulty_level', models.CharField(blank=True, max_length=20)),
                ('difficulty_rating_count', models.PositiveIntegerField(default=0)),
                ('overall_rating_avg', models.FloatField(blank=True, null=True)),
                ('overall_rating_count', models.PositiveIntegerField(default=0)),
                ('original_air_time', models.DateTimeField(db_index=True)),
                ('is_outdoor', models.BooleanField(default=False)),
                ('has_tread_pace_target', models.BooleanField(default=False)),
                ('equipment_tags', models.JSONField(blank=True, default=list)),
                ('is_explicit', models.BooleanField(default=False)),
                ('language', models.CharField(blank=True, default='english', max_length=20)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['discipline', 'class_type_id', 'duration_seconds'], name='workouts_pe_discipl_c54396_idx')],
            },
        ),
    ]
