# Generated by Django 4.2.30 on 2026-10-04 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0039_peloton_class_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='goal_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='programslot',
            name='spec_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='PlanDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed'), ('created', 'Created')], default='generating', max_length=12)),
                ('inputs_json', models.JSONField(default=dict)),
                ('context_text', models.TextField(blank=True)),
                ('spec_json', models.JSONField(blank=True, default=dict)),
                ('picks_json', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('ai_model', models.CharField(blank=True, max_length=60)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workouts.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
