# Generated by Django 4.2.30 on 2026-10-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0040_training_plan_drafts'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandraft',
            name='from_week',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plandraft',
            name='kind',
            field=models.CharField(choices=[('new', 'New plan'), ('reassess', 'Reassessment')], default='new', max_length=10),
        ),
    ]
